### ISSUE TITLE
RPM build - CentOS Stream 9

### ISSUE THREAD

**Issue by StykMartin** [beaker-project/beaker#141]
At this moment it is not possible to create a new RPM build for CentOS Stream 9.
Build is failing in early stage with following error:
```
DEBUG util.py:444:  No matching package to install: 'python3-mock'
DEBUG util.py:444:  No matching package to install: 'python3-nose'
```

It is necessary to investigate why packages are not available and what we will do next.

**Comment by stratakis** [comment]
nose's development has stalled upstream since 2016. It's better to move the project to pytest and the conversion should be simple enough.

As for mock, python includes it in the stdlib so there is no need to use the external library.

**Comment by hroncok** [comment]
See also https://fedoraproject.org/wiki/Changes/DeprecatePythonMock and https://fedoraproject.org/wiki/Changes/DeprecateNose

**Comment by StykMartin** [comment]
That's completely fine. We will fix it, but first it has to be tracked :)

**Comment by rasibley** [comment]
hi @StykMartin ! hope your doing well :-) curious if there is any update on this issue or are we still blocked due to the deprecated packages ?

**Comment by StykMartin** [comment]
Hello @rasibley. I haven't worked on this yet. However, if it is a blocker for you I can dedicate some time and fix the issue.

**Comment by rasibley** [comment]
Thank you @StykMartin ! Yes a bit of blocker for us as we would like to enable upstream kernel testing against the (AutoSD) Automotive Stream Distribution, see https://sigs.centos.org/automotive/#automotive-stream-distribution for more details. Thank you for working on it ! :hugs:

**Comment by StykMartin** [comment]
Just a quick update. It is being worked on this problem. I just need to land a couple of PRs to remove obstacles.

**Comment by rasibley** [comment]
Thank you @StykMartin !

**Comment by rasibley** [comment]
@StykMartin looks like it was merged ! Thank you, should we close the issue and Yariv's issue as well which seems to be a dup ? Also where can I find the c9s Restraint builds ?

**Comment by StykMartin** [comment]
C9 chroot was broken lately quite often therefore I had no chance to properly build stuff. If everything goes well we will have everything resolved by this weekend.

**Comment by Yarboa** [comment]
Thanks you @StykMartin

**Comment by StykMartin** [comment]
```
[root@4e5d275f28a8 /]# cat /etc/centos-release
CentOS Stream release 9
[root@4e5d275f28a8 /]# wget -O /etc/yum.repos.d/beaker-client.repo     https://beaker-project.org/yum/beaker-client-CentOSStream.repo
[root@4e5d275f28a8 /]# yum install beaker-client
Last metadata expiration check: 0:02:08 ago on Tue May 24 17:28:41 2022.
Dependencies resolved.
===================================================================================
 Package                  Arch        Version             Repository          Size
===================================================================================
Installing:
 beaker-client            noarch      28.3-1.el9          beaker-client      195 k
```

The client is in place. Btw, the beaker-client will be part of EPEL-9 as well -https://koji.fedoraproject.org/koji/buildinfo?buildID=1969906

Restraint is on the way as well.

**Comment by StykMartin** [comment]
Client done. Closing ticket. Harness will be done under #150
