### ISSUE TITLE
Clients not available for Fedora 35

### ISSUE THREAD

**Issue by JohnVillalovos** [beaker-project/beaker#146]
This location does not have a client for Fedora 35:

https://beaker-project.org/yum/client/

**Comment by JohnVillalovos** [comment]
@StykMartin Any chance you can generate these files? Thanks.

**Comment by StykMartin** [comment]
@JohnVillalovos just checking what is missing. Can you please share the list of RPMs you missing there?

**Comment by JohnVillalovos** [comment]
> @JohnVillalovos just checking what is missing. Can you please share the list of RPMs you missing there?

Sure

```
rhts-*  I use the 'make bkradd' command
beaker-client
```

Basically the files that are in: https://beaker-project.org/yum/client/Fedora33/

Thanks!

**Comment by StykMartin** [comment]
All files provided for Fedora 35
https://beaker-project.org/yum/client/Fedora35/

Closing now.

**Comment by JohnVillalovos** [comment]
Thanks @StykMartin !!
