### ISSUE TITLE
[BUG] grubport snippet breaks unified grub.cfg setup of CentOS Stream 9

### ISSUE THREAD

**Issue by nomuranec** [beaker-project/beaker#147]
**Describe the bug**  
grubport snippet modifies /boot/efi/EFI/redhat/grub.cfg.  Modification is necessary on EFI system with older distros like RHEL7 and RHEL8.   However since Fedora 34 and CentOS Stream 9, the file should not be modified as it becomes a step stone to the unified grub.cfg, i.e. /boot/grub2/grub.cfg.

**To Reproduce**  
1. Provision CentOS Stream 9 on a system
2. Check /boot/efi/EFI/redhat/grub.cfg

**Actual behavior**  
/boot/efi/EFI/redhat/grub.cfg contains actual boot entries or 'blscfg'.

**Expected behavior**  
/boot/efi/EFI/redhat/grub.cfg should look something like this:
```
search --no-floppy --set prefix --file /boot/grub2/grub.cfg
set prefix=($prefix)/boot/grub2
configfile $prefix/grub.cfg
```

**Additional context**  
About unified grub.cfg setup
https://fedoraproject.org/wiki/Changes/UnifyGrubConfig

**Comment by StykMartin** [comment]
Resolved by #148.
