### ISSUE TITLE
Clients and harness not available for Fedora 37

### ISSUE THREAD

**Issue by mh21** [beaker-project/beaker#169]
FC37 has been released 🎉, but the Beaker client and harness don't have repos for it at https://beaker-project.org/yum/client/ and https://beaker-project.org/yum/harness/:

![image](https://user-images.githubusercontent.com/755362/204236579-2fcdc4ec-c287-4f1b-bfa0-f93112f3bf03.png)

This is a similar issue as https://github.com/beaker-project/beaker/issues/146.

@StykMartin would that be something you could look into, or can we sent a PR somewhere to fix it?

**Comment by StykMartin** [comment]
Hello @mh21. Restraint builds are manually synced to the upstream node. I need to create a new build and I store it there.
If chroot is ready it should be quite simple.

**Comment by mh21** [comment]
I updated the title and description to clarify that this also affects the harness repos at https://beaker-project.org/yum/harness/.

**Comment by mh21** [comment]
friendly ping @StykMartin @cbouchar

FC35 is the latest Fedora version that has client/harness repos, and is going EOL tomorrow 🙈

**Comment by StykMartin** [comment]
Well, I guess It is about time to store new RPMs if FC35 is dead 🫣.
In the morning I created all builds, I need to sync them upstream.

**Comment by StykMartin** [comment]
F36/F37 stored. I haven't run any smoke tests yet.

**Comment by mh21** [comment]
> F36/F37 stored. I haven't run any smoke tests yet.

The client repo at https://beaker-project.org/yum/client/ is still missing them for FC37?

**Comment by StykMartin** [comment]
Oh.. I completely forgot Beaker Client. Is it really necessary to store it for FC there? I'm always building it directly to Fedora, but I can sync it

**Comment by mh21** [comment]
> Oh.. I completely forgot Beaker Client. Is it really necessary to store it for FC there? I'm always building it directly to Fedora, but I can sync it

Sorry I didn't know that 🤦. If the official Fedora repos are the canonical way to get the client for Fedora, we should totally switch to that. Maybe it makes sense to update https://beaker-project.org/download.html with that info 🤗?

**Comment by StykMartin** [comment]
I'm keeping a client here - https://src.fedoraproject.org/rpms/beaker (part of FC). As you can see it is always up-to-date. 
I will reconsider if there is any use case now to use BP.org. From the top of my mind, I don't see any right now.

I'll think about that and update BP.org accordingly.

**Comment by mh21** [comment]
Thank you! From our side, the ticket is resolved. I'll leave it open so you can decide how to track the beakerproject.org changes 🤗

**Comment by StykMartin** [comment]
Tracked here - https://github.com/beaker-project/beaker-project.org/issues/39. 

Closing. Thank you @mh21 !
