### ISSUE TITLE
[BUG] downloadable PDF documentation is missing

### ISSUE THREAD

**Issue by pbunyan** [beaker-project/beaker#208]
**Describe the bug**  
Downloadable PDF documentation is missing

https://beaker-project.org/docs/user-guide.pdf
404 Not Found
Not Found
The requested URL /docs/user-guide.pdf was not found on this server.

https://beaker-project.org/docs/admin-guide.pdf
404 Not Found
Not Found
The requested URL /docs/admin-guide.pdf was not found on this server.

**To Reproduce**  
https://beaker-project.org/docs/user-guide.pdf
https://beaker-project.org/docs/admin-guide.pdf

**Actual behavior**  
The PDFs are missing

**Expected behavior**  
Access to the Beaker documentation in PDF format

**Screenshots**  

**Additional context**  
We can reach the documentation here
https://beaker-project.org/docs/user-guide/
https://beaker-project.org/docs/admin-guide/

But scrolling/clicking thru the html pages is not user friendly.
Please bring back the PDF format :)

**Comment by StykMartin** [comment]
I will try to rebuild it :)

**Comment by StykMartin** [comment]
@pbunyan, since we don't have this for Release 29 at this moment, you can use 
https://beaker-project.org/docs-release-28/user-guide.pdf
https://beaker-project.org/docs-release-28/admin-guide.pdf

It is quite similar, except for the alembic, of course.

**Comment by pbunyan** [comment]
Its great to know the Beaker God is still out there :)
The PDF documentation has always been a great resource for the Beaker users.
Thank you for keeping it up to date and available.

Thank you!  :)

**Comment by StykMartin** [comment]
And it is done.
![image](https://github.com/beaker-project/beaker/assets/188918/255605d5-bc9e-4f4f-9d59-9559fef889ca)

https://beaker-project.org/docs/user-guide.pdf
https://beaker-project.org/docs/admin-guide.pdf

**Comment by pbunyan** [comment]
Excellent!
Thank you Martin!
