### ISSUE TITLE
[RFE] Ability to control key,value over the HTTP API

### ISSUE THREAD

**Issue by beraldoleal** [beaker-project/beaker#55]
**Is your feature request related to a problem? Please describe.**

Hi all, I'm part of virt team at RH and we provide machines to the virt team with Beaker, using both automatic and manual. I'm not sure if this is the proper place and/or this is something that is already implemented, but we haven't found a nice solution yet, So, for us, would be nice to have better visibility of our loans to avoid having idle machines in someone's held. An automatic user notification, to check if we can get back the machines (even when using the manual) would be nice. With more control about the notification system (message, when, ignore flags, etc..).

**Describe the solution you'd like**

We are thinking about creating some kind of command-line wrapper/client to beaker to get some information and act on. Not sure if the "key,value" feature was designed to that, but we thought that we could use this to store some information (like tags) and get this via HTTP API. Looking to the project documentation we haven't found ways to see/change the 'key, value' information. Is that possible today? Or to be implemented?

**Describe alternatives you've considered**

Would also be nice to have more control over the loan on the web interface (for instance: how long do you intend to use this machine?)

Thanks in advance

**Comment by StykMartin** [comment]
Hello @beraldoleal,

Thank you for reaching out to us.


There is no plan to expose and give control of `Key/Value`. `Key/Value` are feed with additional details about system, rather user-defined variables. I believe we provide a lot of different mechanisms on how to "tag" machine. For example, you can use `pools` and combine them with `ACL(s)`.
